FROM docker.io/nvidia/cuda:12.8.1-devel-ubuntu24.04

RUN apt-get update && apt-get install -y build-essential xutils-dev bison zlib1g-dev flex libglu1-mesa-dev git \
    python3 python3-venv wget file libfftw3-dev \
    cmake ninja-build diffstat \
    clang libgtest-dev clang-format
